mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Persona(models.Model):
    nombre = models.CharField(max_length=25)
    email = models.EmailField()

    def __str__(self):
    	return self.nombre

class Tarea(models.Model):
    titulo = models.CharField(max_length=25)
    descripcion = models.CharField(max_length=200)
    persona_asignada = models.ForeignKey(Persona, on_delete=models.CASCADE)

    def __str__(self):
    	return self.titulo

polls/views.py
from django.shortcuts import render, HttpResponse
from django.utils import timezone
from .models import Tarea


def home(request):
	lista_ultimas_tareas = list(Tarea.objects.all())
	return render(request, 'polls/index.html', {'lista_ultimas_tareas': lista_ultimas_tareas})

polls/templates/polls/detail.html
<h1>{{ tarea.titulo }}</h1>
<ul>
{% for tarea in tarea.tarea_set.all %}
    <li>{{ persona.nombre }}</li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">

</head>

<body>

<h1>Tareas</h1>



    {% if lista_ultimas_tareas %}
        <ul>
        {% for tarea in lista_ultimas_tareas %}
            <div id="bloque">
                <a id="titulo" "/polls/{{ tarea.id }}/">Título: </a>
                <a>{{ tarea.titulo }}</a>
                <br>
                <a id="descripcion" "/polls/{{ tarea.id }}/">Descripción: </a>
                <a>{{ tarea.descripcion }}</a>
                <br>
                <a id="asignada"  >Persona asignada a la tarea:</a>
                <a "/polls/{{ tarea.id }}/">{{ tarea.persona_asignada }}</a>
                <br>

                <i class="fa fa-envelope" style="font-size:36px"></i>

                <a id="email" href= mailto:{{tarea.persona_asignada.email}}>{{ tarea.persona_asignada.email }}</a>

             </div>
            <br>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}


</body>

</html>